### ISSUE TITLE
Request Android TV "app"

### ISSUE THREAD

**Issue by crak3rjack** [LuisLDA/DLMoviesApp#1]
Sería posible crear de está página web, tiene un catálogo bien completo de películas y tv series. Trae subtitulos y calidad para escoger es en inglés y gracias.
https://goku.to/

**Comment by LuisLDA** [comment]
Saludos 👋 si es posible sin embargo los servidores que utiliza la web puede que tengan ciertas restricciones por lo que puede requerir tiempo para poder extraer los videos directos.

**Comment by crak3rjack** [comment]
@LuisLDA Espero qué se pueda lograr, estaré por aquí pendiente de cualquier información y gracias.🙏💪
